version: '3.7'

services:

  nginx:
    container_name: swc-pss
    image: swc-pss
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PACKAGES: "nano wget curl"
    ports:
      - "80:80"
    networks:
      - nodeapp-network
    volumes:
      - ./logs:/var/www/logs
    environment:
      - NODE_ENV=production
      - APP_VERSION=1.0

networks:
  nodeapp-network:
    driver: bridge